# Generated by Django 2.2.13 on 2020-10-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='job',
            name='year',
        ),
    ]
