# Generated by Django 2.2.13 on 2020-10-06 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0007_remove_taskresult_hidden'),
        ('jobs', '0002_auto_20201005_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='resultid',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='jobid', to='django_celery_results.TaskResult'),
        ),
    ]
