# Generated by Django 2.2.13 on 2020-10-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_resultid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='resultid',
            field=models.CharField(max_length=100),
        ),
    ]
