# Generated by Django 2.2.13 on 2020-10-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20201006_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='hash',
        ),
    ]
